<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Mono.Cecil" Version="0.11.6" />
      <PackageReference Include="System.Reflection" Version="4.3.0" />
      <PackageReference Include="System.Reflection.Extensions" Version="4.3.0" />
      <PackageReference Include="System.Reflection.TypeExtensions" Version="4.7.0" />
    </ItemGroup>

</Project>
